language: csharp
solution: DesignPatterns.sln
install:
  - nuget restore DesignPatterns.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory packages
script:
  - xbuild /p:Configuration=Release DesignPatterns.sln
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DesignPatterns.Test.TestDrivenDevelopment/bin/Release/DesignPatterns.Test.TDD.dll