language: csharp
solution: DesignPatterns.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore DesignPatterns.sln
after_script:
  - nunit-console DesignPatterns.Test.TDD/bin/Release/DesignPatterns.Test.TDD.dll